### ISSUE TITLE
ایجاد تیکت معرفی کسب و کار به مشتری

### ISSUE THREAD

**Issue by m-farokhtabar** [m-farokhtabar/CitywareAndroidClient#11]
پس از جستجوی کاربر مورد نظر با انتخاب کاربر از لیست جستجو 
گزینه معرفی کاربر به کسب و کار زده می شود پس از آن در جواب یک شماره تیکت، تاریخ اعتبار و اطلاعات مربوط به میزان تخفیفات بر خواهد گشت که در یک فرم نمایش داده میشود و همچنین امکان Share ان نیز وجود داشته باشد

**Comment by larsahajar** [comment]
کد های سمت اندروید زده شده فقط تست نهایی مونده که اول باید کدهای سمت وب سرویس درست میشد
