### ISSUE TITLE
تغییر نحوه نمایش پکیج های خریداری شده

### ISSUE THREAD

**Issue by m-farokhtabar** [m-farokhtabar/CitywareAndroidClient#2]
با توجه به تغییرات وب سرویس 

- ویومدل  پکیجهای خریداری شده تغییر کرده است
که دو سرویس لیست پکیج های معتبر و پکیج های منقضی شده اضافه شده
فرم نمایش پکیج های کاربر بایستی به دو قسمت پکیج های فعلی(معتبر) و پکیج های منقضی شده تقسیم گردد
بهتر از TabView استفاده شود با استفاده از دو فرگمنت....

**Comment by m-farokhtabar** [comment]
همچنین ویومدل پکیج های خریداری نیز تغییر کرده که باید به روز شود

**Comment by larsahajar** [comment]
من بجای تب از دکمه استفاده میکنم
