### ISSUE TITLE
صفحه اصلی

### ISSUE THREAD

**Issue by m-farokhtabar** [m-farokhtabar/CitywareAndroidClient#9]
در این صفحه  چیزی شبیه به صفحه اول بازار داشه باشیم

- [ ] بنر در بالای صفحه به تعداد دلخواه که با قابلیت کلیک ممکن است به یک صفحه وب یا به یک اکتیویتی برنامه برود

- [ ] لیست کسب و کار های مورد علاقه کاربر

- [x] لیست جدیدترین پوسترها ی کسب و کارها

- [x] لیست پر بازدیدترین ها کسب و کارها

- [ ] بنر در وسط صفحه به تعداد دلخواه که با قابلیت کلیک ممکن است به یک صفحه وب یا به یک اکتیویتی برنامه برود

- [x] لیست پرامتیاز ترین کسب و کارها

**- البته یک اکتیوتی جدا هم درست بشه که هر کدام از این لیست را خواست کاملش رو ببینه توی اون لیست کامل روببینه به غیر کسب و کار های مورد علاقه کاربر که خودش اکتیویتی داره**

**Comment by larsahajar** [comment]
فکر کنم تغییراتی توی طراحی برنامه درنظر گرفتید و اینجا اعمال نکردید
اصلا صفحه شبیه صفحه اول بازار نیست
